import {
  pgTable,
  text,
  timestamp,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { classes } from "./classes";

/**
 * Structural mirror of the LessonPlan Zod type exported from
 * packages/llm/src/prompts/generate-lesson-plan.ts.
 *
 * Declared locally rather than imported from @mindmap/llm to keep
 * @mindmap/db dependency-free of the LLM layer (the dependency graph is
 * strictly llm -> db typing, not db -> llm). The Zod schema in
 * generate-lesson-plan.ts is the authoritative source of truth — this type
 * is a compile-time convenience for the jsonb $type<>() annotation.
 */
export type LessonPlanJson = {
  theme: string;
  commonMisunderstanding: string;
  targetUnderstanding: string;
  suggestedActivities: Array<{
    title: string;
    description: string;
    referencedMisconceptionIds: string[];
  }>;
  discussionPrompts: string[];
  confrontationApproaches: string[];
};

/**
 * theme_lesson_plans — Plan 08-04 / LSPL-02 / D-10, D-16, D-17, D-18.
 *
 * Stores teacher-facing lesson plans generated by the @mindmap/llm
 * generateLessonPlan prompt builder. This is the ONLY new table introduced
 * in Phase 8 (D-10): themes and constituent misconceptions live in YAML,
 * and per-class aggregate views are derived at query time from
 * diagnostic_sessions.
 *
 * CACHE SEMANTICS
 *
 * The composite lookup index on (classId, themeId, dataHash) is the cache
 * key. `dataHash` is a SHA-256 digest of the current set of per-misconception
 * counts for this theme in this class (see apps/web/lib/theme-cache-hash.ts).
 *
 * - Cache HIT: `findFirst({ where: classId+themeId+dataHash, orderBy:
 *   desc(generatedAt) })` returns the most-recent matching row — no LLM call.
 * - Cache MISS (data has changed): no matching row, call generateLessonPlan,
 *   INSERT a new row (D-18: never UPDATE — history is preserved).
 * - Force regenerate: skip the lookup, always INSERT a new row. Previous
 *   rows remain so a teacher can compare plans over time.
 *
 * IMPORTANT — why this is NOT a unique index (CR-01 fix):
 *
 *   D-18 says "force regenerate always INSERTs a new row". When the
 *   underlying class data has not changed between two regenerate clicks,
 *   both rows share the same (classId, themeId, dataHash) tuple — so a
 *   UNIQUE constraint on that tuple would reject the second INSERT and
 *   crash the regenerate path at runtime. We therefore use a plain
 *   `index()` here: duplicate (classId, themeId, dataHash) rows are
 *   allowed, and the cache read picks the newest via
 *   `orderBy: [desc(generatedAt)], limit: 1`. Append-only history
 *   semantics are preserved; the unique-constraint bug is gone.
 *
 * The secondary (classId, themeId) index supports cheap "show me every plan
 * I've ever generated for this theme" lookups without scanning by hash.
 *
 * NO FK ON THEME_ID
 *
 * themeId is a library slug (e.g. "substance-based-reasoning"). Themes live
 * in packages/misconceptions/data/themes.yaml and have no SQL home, so
 * themeId is a plain text slug — never an FK. Library integrity is enforced
 * by the THME-02 orphan-theme CI check, not by the DB.
 *
 * PITFALL 3 — JSONB DEFAULT BUG
 *
 * The `lessonPlan` column is `jsonb().notNull()` with NO `.default(...)`.
 * Drizzle 0.45 has a jsonb default bug (see diagnostic-sessions.ts:49 and
 * 08-RESEARCH.md Pitfall 3) where `.default({})` emits a SQL literal that
 * Postgres rejects on INSERT. Every caller of db.insert() MUST supply the
 * full lesson plan body — there is no server-side fallback.
 */
export const themeLessonPlans = pgTable(
  "theme_lesson_plans",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    classId: text("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    // Library slug — NOT an FK (themes live in YAML; integrity via THME-02).
    themeId: text("theme_id").notNull(),
    // SHA-256 hex of the canonical (misconceptionId, studentCount,
    // unresolvedCount) tuples, sorted. See apps/web/lib/theme-cache-hash.ts.
    dataHash: text("data_hash").notNull(),
    // Zod-validated LessonPlan object from packages/llm/src/prompts/generate-lesson-plan.ts.
    // NO default — Drizzle 0.45 jsonb-default bug per Pitfall 3.
    lessonPlan: jsonb("lesson_plan").$type<LessonPlanJson>().notNull(),
    generatedAt: timestamp("generated_at", {
      withTimezone: true,
    }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  },
  (t) => [
    // Cache key: lookup by (class, theme, dataHash) selects the newest plan
    // for a given data fingerprint. NOT unique — see the "IMPORTANT — why
    // this is NOT a unique index (CR-01 fix)" docblock above. Callers MUST
    // `orderBy: [desc(generatedAt)], limit: 1` on the cache read.
    index("theme_lesson_plans_class_theme_hash_idx").on(
      t.classId,
      t.themeId,
      t.dataHash
    ),
    // Secondary lookup: list every plan ever generated for a (class, theme)
    // pair, regardless of data fingerprint (history browsing).
    index("theme_lesson_plans_class_theme_idx").on(t.classId, t.themeId),
  ]
);
